### ISSUE TITLE
Error on Windows 10 + JDK 11.0.3

### ISSUE THREAD

**Issue by jflefebvre06** [mattsheppard/gethostname4j#4]
Hello,

When I switch from JDK8 to JDK11 I get then folloging error on Windows 10 :

`java.lang.UnsatisfiedLinkError: D:\Profiles\XXX\AppData\Local\Temp\jna--1023426020\jna11360057893049336703.dll: Can't find dependent libraries`

Works fin on Windows 7 and unix plateform

**Comment by mattsheppard** [comment]
I would guess that it requires updating the version of JNA (4.2.2 seems to be what we're using now, 5.3.1 is the latest according to https://github.com/java-native-access/jna/blob/master/CHANGES.md).

I don't have a windows 10 box to test with - Any chance you could bump the version in the pom, rebuild it and let me know how you go?

We'll need to check out what JDK versions the latest JNA version supports if that does fix it because if they've dropped JDK6 support then Issue #1 would break as a result.

**Comment by jflefebvre06** [comment]
Hello
I confirm works fine with the last jna version

**Comment by mattsheppard** [comment]
Ok - If I've done things right a 0.0.3 version should be released to maven central now which depends on the latest JNA.

Maven central can take a while to reflect changes, so it might take a little while to show up on https://search.maven.org/search?q=a:gethostname4j

**Comment by jflefebvre06** [comment]
Perfect thanks a lot
